### PR TITLE
Add fsm application - separate FSM stack

### PR DESCRIPTION
**Pull request by maxsocl**
@cjlee112  @auraz

PR summary:
* FSM stack was separeted - moved to `fsm` application.
* There is no data migration in this PR because we decide not to migrate FSM data but there is an issue:
  * in fixture dump file we have FSM entries to populate our database and as I see this entries (FSM, FSMNode) needed to start Course progress;
  * so we need to decide how to migrate this data;
  * alternatively we can load fixtures again to a clean database;
* I have changed  `debug-e.json` fixture file by manual change fsm instances path - from `ct` to `fsm`, so we can load fixture to get all example data including FSM entries.
* I try to figure out how to test `deploy` and `deploy_all` function from `fsmspec` plugin but I can't. Can you point me to action when this functions can be tested? Thanks.

### CODE REVIEW

**Comment by cjlee112** [comment]
@maxsocl ct/fsm_plugin/add_lesson.py etc. should stay in ct/fsm_plugin rather than moving to fsm/fsm_plugin, since these are specific to the ct module.  The value of making fsm a separate app is that it should (eventually) work with any Django app (i.e. you could add an fsm_plugin directory to any Django app, and put some FSM specifications there).  

One exception: fsm/fsm_plugin/testme.py makes sense to keep in that location.

I think fsmspec.py should be in the fsm directory rather than fsm/fsm_plugin, since it is actually not a plugin, but rather "base" code.

**Comment by maxsocl** [comment]
I have rewrited `deploy` and `deploy_all` in this manner:
https://gist.github.com/maxsocl/d7c54024c9ce3c885643

I have added app_name param to pass to `deploy` func.

But in fsm.models.py we have `get_plugin` func than is called from FSM.save_graph and PluginDescriptor.__get__ methods but there is no chanсe to get application name at this point in a simple way. So I think I need to add application searching via glob.glob in `get_plugin` func to find app_name something like in this gist:

https://gist.github.com/maxsocl/9e4fbfdb700a71f3e426

But there is one issue. If we can have two same plugins in different application - will be catched first one. Does it posible to have two plugins with the same name?

Thanks.

**Comment by cjlee112** [comment]
@maxsocl I think we should store the full plugin path in FSMNode.funcName, i.e. instead of funcName='lessonseq.LESSON', it would store funcName='ct.fsm_plugin.lessonseq.LESSON'.  I'll add a commit on top of your fsm_app branch showing that.

**Comment by cjlee112** [comment]
@maxsocl RE: FSM naming, every FSM must have a unique name.  But there is no reason why we could not adopt a convention that says every FSM should have a name of the form 'APP.NAME' where APP is the name of the app, and NAME the name of the FSM within that app... which would eliminate the possibility of name collisions between FSMs from different apps.

**Comment by cjlee112** [comment]
@maxsocl Might be simpler to have deploy() just take complete module name, e.g. 'ct.fsm_plugin.lessonseq',  I'll add a commit on your fsm_app branch to show that approach...

**Comment by maxsocl** [comment]
@cjlee112 I have added you proposed implementation to store module full path but was blocked by the need to re-deploy plugins because now I got as Exception `No module named lessonseq` when I start to study some unit.
In Pdb I can see the following:

>(Pdb) funcName
>u'lessonseq.START'

So I need to re-deploy modules to store full modules path in funcName (node.funcName).
Can you provide re-deploy modules documentation to move on?
Thanks.

**Comment by maxsocl** [comment]
@cjlee112 I found that I can simply do the following to update nodes data (node.funcName):
```python
for node in deploy_all('admin'):
    node.save()
```

Can I use this method to move on to test new code?
Thanks.

**Comment by maxsocl** [comment]
@cjlee112 I found that I can simply do the following to update nodes `funcName` attributes (including for `testme` plugin) and move on in testing:

```python
from fsm.fsmspec import deploy_all
deploy_all('admin', ignore=('__init__'))
```
Is this a right way to re-deploy modules?
Thanks.

**Comment by cjlee112** [comment]
@maxsocl Yes, that's exactly how you deploy FSM specs, either to deploy a new FSM or to alter the existing FSM specs.

**Comment by cjlee112** [comment]
@maxsocl I am merging your fsm_app_review branch (which contains this PR) to master, then will close this PR.

**Pull request merged**
