### PR TITLE
Lti release

### PR DESCRIPTION
**Pull request by auraz**
This PR adds LTI support along with UX improvements

Docs describing Moodle integration: https://docs.google.com/document/d/1LSTRlqZDTxVtDQSKQq-n2XYncMWyt3hBPHyPVJyP15A/edit

@cjlee112 FYI

### CODE REVIEW

**Comment by cjlee112** [comment]
Based on an initial superficial glance through the code, it looks pretty good for the planned demo deployment.  I have a few initial questions:

* the list of package requirements (in requirements.txt) has grown enormously, from something like 4 packages in the previous release, to something like 30 in your branch.  I'd like to ascertain which of these are truly required for *production* (some appear to be for testing purposes), vs. which are needed for *developers* (e.g. testing and coverage tools), and to review whether any of these maybe should not be required.  Python package management remains unfortunately one of Python's weak points, and such a long list of requirements increases the chances of an install problem.

* Your "Settings for MOODLE LTI" instructions simply say "Install all dependencies from requirements.txt" without explicitly saying how.  If the whole procedure is just "pip install foobar" for each package name, it should say so... but in reality I imagine it will be more complex than that. 

* Your "Settings for MOODLE LTI" instructions make it sound like each instructor will have to paste our LTI consumer key and secret into the MOODLE External Tool form for their course.  Is that correct, and if so, does this represent a basic security problem? (if all our users know the secret, then it's not a secret anymore and confers no security).  Seems like I am missing something here.

* it would be helpful if the LTI consumer key and secret were commented in settings_local.py with details about the key length and character set we should use for generating random keys.

* the ct:subscribe URL '/ct/courses/subscribe/COURSE_ID/' seems a bit inconsistent with our URL patterns.  It seems more consistent to make it ''/ct/courses/COURSE_ID/subscribe/'

**Comment by cjlee112** [comment]
FYI this PR implements issue #25.

**Comment by cjlee112** [comment]
@auraz Why does this PR only include 3 commits?  It seems to have squashed the entire previous project history into one single commit feed85b.  Unless there is a real reason to squash history, I prefer to retain the true commit history of the work.

**Comment by auraz** [comment]
@cjlee112 We have created new branch (release_lti), squashed commits here, and created PR.
PR to master, that we will open next week, we will do from our develop branch, were all history is preserved.

**Comment by maxsocl** [comment]
@cjlee112 I will try to answer your questions:

**List of package requirements.**

This list is created using the following command to ensure that current package state will be frozen and we don't lose anything.
```shell
pip freeze > requirements.txt
```
`pip freeze` command create a list of packages that are installed in system or in virtualenv including all dependencies.
Also `pip freeze` freeze versions of all packages that is a good practice.

We can use different files for production, development etc.
I have created two new files and I can add that files in next commit:

    prod_requirements.txt
    dev_requirements.txt

All of packages in prod_requirements.txt are used in production:

    Django==1.7.8
    PyJWT==1.1.0
    amqp==1.4.6
    anyjson==0.3.3
    beautifulsoup4==4.3.2
    billiard==3.3.0.20
    celery==3.1.18 # Distributed Task Queue
    django-crispy-forms==1.4.0
    httplib2==0.9.1
    -e git+https://github.com/mitodl/ims_lti_py.git@d96a6201cf3b63b9e1b33780ef5e29bc65242ceb#egg=ims_lti_py-origin # LTI python implementation
    kombu==3.0.26
    lxml==3.4.4
    mock==1.0.1 # mock for testing
    oauth2==1.5.211
    oauthlib==0.7.2
    pypandoc==0.9.7
    python-openid==2.2.5
    python-social-auth==0.2.7 # social authentication/registration mechanism
    pytz==2015.2
    requests==2.7.0
    requests-oauthlib==0.5.0
    six==1.9.0
    wikipedia==1.4.0


Some of them are only dependency. For example when we install packages from Socraticqs2 wiki at the end we have got this list:

    Django==1.8.1  # main package
    beautifulsoup4==4.3.2
    django-crispy-forms==1.4.0  # main package
    pypandoc==0.9.7  # main package
    requests==2.7.0
    wikipedia==1.4.0  # main package

And dev_requirements.txt contains additional four packages for development use:

    ipython
    nose
    django-nose
    coverage

**Installation of packages**

To install all list of packages:
```shell
pip install -r requirements.txt
```
If the system is missing some packages - we need to install them.


**MOODLE External Tool and key/secret**

That is a correct way in the Instructor case without pre-configured External Tools.
Administrator can pre-config (enter key/secret, launch url) External Tool for the Instructor. Then Instructors can create tool using pre-configured one.
But at Test server I can't try this functionality.

http://developers.imsglobal.org/tutorials.html

>For the Instructor use case, they generally add a LTI tool into their course structure as a resource   link using the LMS control panel. The instructor enters the URL, **secret**, and **key** into as meta data for the resource link. When students select the tool, the LMS uses the URL, secret, and key information to seamlessly launch the student into the remote tool in an iframe or new browser window.

>For the Administrator use case, they generally add a "virtual tool" to the LMS, entering the URL, **secret** and **key**. Once this is done, Instructors simply see the newly configured LTI tool as another tool or activity to be placed as a resource link in their course structure. The Instructors and students may not even be aware that the tool they are using is running out side of the LMS. They simply select and use the tool like any other tool that is built-into the LMS.


**Details about the key/secret in settings_local.py**

There key/secret is used in OAuth protocol and there is no such strict restrictions.
Key/secret can be any random python string with enough length and I will add this as comment into settings_local.py.


**Subscribe url pattern inconsistency**

Yes, thanks for this notation - I will correct this.

**Comment by cjlee112** [comment]
Can you please explain and document LTI_URL_FIX in settings_local.py?  Presumably this is just for developer-tests?  Do we need this for our production server (which uses https)?  If we do need this, please describe what exactly it does.

**Comment by cjlee112** [comment]
Hmm, I migrated our standard developer test database to the lti_release schema, but I'm hitting two unexpected issues when I try to login to the server (running in runserver debug mode):

* trying to login with the standard developer login ("admin") and password fails to login.  No error message is shown, but it just re-displays the login page.

* the login page is still displaying the (five) social-auth signin buttons that I thought we were hiding in this demo release.  Why?

**Comment by auraz** [comment]
@cjlee112 I do not think you need LTI_URL_FIX.

**Comment by auraz** [comment]
This PR was not merging, can you please confirm that you're using right branch.
Regarding login, it is strange. Code changes should not touch users database

**Comment by cjlee112** [comment]
I'm wondering whether the login problem I'm experiencing is due to some aspect of how session cookies are configured in the lti_release branch?  On Firefox cookies I see localhost:sessionid cookie configured as "Send For: Encrypted connections only".  But of course for my developer test server I'm running it just as http (as I always have).  In that case the browser may be refusing to send the sessionid which of course the server will interpret as "user not logged in".

When I run my master branch as developer server, sessionid cookie is configured as "Send For: Any type of connection".  So I suspect that is what's screwing up login on lti_release.

**Comment by cjlee112** [comment]
My test of lit_release is on commit bfe1ae

**Comment by auraz** [comment]
@cjlee112 you need to pull branch, here are 3 commits more. I was thinking that today we will merge this PR, and it will be part of your develop branch. That's why we were adding commits yesterday and today to this branch

**Comment by auraz** [comment]
Let me reproduce.

**Comment by cjlee112** [comment]
I think I see the cause of the problem.  Your recommended settings_local.py set SESSION_SERIALIZER to use PickleSerializer instead of the usual JSONSerializer.  PickleSerializer is insecure, and Django compensates by defaulting session storage to only be sent of https.

**Comment by auraz** [comment]
@cjlee112 good that you've figured it, I had no idea and started to run stuff.

**Comment by cjlee112** [comment]
Ooops.  It also sets SESSION_COOKIE_SECURE = True
Sorry I didn't notice that before.

**Comment by cjlee112** [comment]
OK, now I can login.

**Comment by auraz** [comment]
@cjlee112 Nice, sorry for inconvenience.

**Comment by cjlee112** [comment]
@maxsocl Why does your settings_local.py set SESSION_SERIALIZER to use PickleSerializer?  This is insecure and deprecated.  Definitely don't want to use this for production, and I don't see why we should use it for developer testing either.   Why did you change this from the standard JSONSerializer?

**Comment by cjlee112** [comment]
I am able to get CCLE to launch LTI external tool to my developer install of lti_release, as long as I set Launch Container to "New window" (makes me very happy).  If use "default" or "embed", I see a blank frame.

**Comment by maxsocl** [comment]
@cjlee112 
**`SESSION_COOKIE_SECURE = True`** is to force the use of HTTPS. For local development without LTI Consumer testing we can disable this option. There is a cause of your login problem. Sorry for inconvenience.

Second problem with a **blank frame** - you can't load insecure content within secure site. Google tells us this - "This frame was blocked because it contains some insecure content." We need to use HTTPS to load X-FRAME within HTTPS site.

**SESSION_SERIALIZER** - it is an old option from my development quests... I forget to remove it. Sorry for this.

**Social button issue** - according to `Settings for Moodle LTI consumer and Socraticqs2 LTI provider` document you need to comment all not needed social-auth to disappear on all pages.

    AUTHENTICATION_BACKENDS = (
       # 'social.backends.twitter.TwitterOAuth',
       # 'social.backends.facebook.FacebookOAuth2',
       # 'social.backends.google.GoogleOAuth2',
       # 'social.backends.linkedin.LinkedinOAuth2',
       # 'social.backends.khanacademy.KhanAcademyOAuth1',
       # 'social.backends.email.EmailAuth',
       'django.contrib.auth.backends.ModelBackend',
    )

**Comment by maxsocl** [comment]
@cjlee112 
**PickleSerializer** issue:
I user PickleSerializer due to this
https://docs.djangoproject.com/en/1.7/topics/http/sessions/#django.contrib.sessions.backends.base.SessionBase.set_expiry

I set expiration date using timedelta so I need to user PickleSerializer.
If you don't want to user Pickle - I will rewrite session expiration logic to be compatible with JSONSerializer :thumbsup:

P.S. PickleSerializer is a trade-off between convenience and security. Ok. But it is deprecated in Celery not in Django.

**Comment by cjlee112** [comment]
RE: PickleSerializer, I was referring to this passage from the Django docs about why Django no longer uses PickleSerializer as its default: "Even with the caveats described in Write Your Own Serializer, we highly recommend sticking with JSON serialization".  If all we need is to store an expiration date, might django.core.serializers.json.DateTimeAwareJSONEncoder be a good solution?

**Comment by cjlee112** [comment]
I think we need to decide on a clean mechanism for managing production vs. developer settings, drawing upon consensus Django best practices.  E.g. what do you think of option 2 in this summary?

http://www.sparklewise.com/django-settings-for-production-and-development-best-practices/

**Comment by maxsocl** [comment]
RE: **PickleSerializer** Yes off course, DateTimeAwareJSONEncoder is a good choice. I need to think about it.

RE2: **Environment-based settings** I have reviewed this solution today. It is a good solution. But we have to think about the number of options that vary based on the environment. In our case there is not so many different options. But in future we may have more different options, so I agree that we need to review this case.

**Comment by cjlee112** [comment]
The courselets.org production server is now running my latest lti_release code, and looks fine at least to a first glance, and launching an LTI link from CCLE.  I think this is enough for me to work on my demo for Tuesday.  I may have more questions over the weekend as I try to put the demo together...

**Comment by cjlee112** [comment]
There are multiple problems with changes to bootstrap usage in the lti_release branch.  I first noticed this because some UI elements started looking bizarre and ugly.  Then I noticed changes to portal.html and base.html, which contain errors such as the following:

* moved bootstrap.min.js link around in ways that break it.
* created multiple links to bootstrap.min.js in different files.
* introduced links to incompatible versions of boostrap in different places (3.1.1 vs. 3.2.0).
* linked to bootstrap.min.js without first linking jQuery, which it depends on.
* introduced basic confusion about correct policy for where to link bootstrap resources: in base?  in portal?  In both?  Why?

**Comment by maxsocl** [comment]
@cjlee112 
**linked to bootstrap.min.js without first linking jQuery.** - this warning I had planned to close in cleaning step.

What you mean when you say that bootstrap.js is broken? Because bootstrap was loaded in portal.html later correctly.

I think that all imports need to present in base.html because basically we need jquery and bootstrap js everywhere and in case when we don't want to import big portal.html template but want to use bootstrap and jquery (this is done in commit https://github.com/raccoongang/socraticqs2/commit/c675b31efa33809929db010b83c0a9c945a8a4f2).

**Ugly elements** - can you specify that elements. This might be caused by custom styles in portal.html. But I can't find elements this styles is transforming.

I apologize for duplicate imports of bootstrap.js and bootstrap.css - I had planned to close this point in cleaning/re-factoring step and actually this point is done in https://github.com/raccoongang/socraticqs2/commit/c675b31efa33809929db010b83c0a9c945a8a4f2

**Pull request closed without merging**
