### PR TITLE
Fsm

### PR DESCRIPTION
**Pull request by wenyaowu**
I changed the path of template and database in /mysite/setting.py using BASE_DIR which stores the path to the directory in which the user’s setting.py module will be contained. In this way, user don't need to config(change) the path themself when first start developing.

For the documentation, I edit the section "Using Github for Windows / Mac"

### CODE REVIEW

**Comment by cjlee112** [comment]
Thanks, Evan!  Getting rid of the hard-coded paths from settings.py seems like a great improvement.  Makes me wonder why this isn't standard Django practice, instead of the instructions to "Don't forget to use absolute paths..." that they include in the default settings.py.

Thanks also for the docs revisions!

Minor point of process: in the future, could you file separate pull requests when you have multiple distinct changes?  That way I can respond and address them separately.  In this case it looks like some of your changes are on the master branch (settings.py) whereas others are on the fsm branch (docs revisions).  I'm not even completely sure what happens when I merge a pull request that affects multiple branches...  Presumably it will update both branches independently...  I will pull the trigger and find out.

**Comment by cjlee112** [comment]
Hi Evan,
I think I'll cherry-pick your docs revisions 2eddf5 and aa75ae, so as to leave out your test commits that added and then deleted test.txt.

**Comment by cjlee112** [comment]
Oops, never mind my comment about multiple branches being affected.  I had seen your commit on master and assumed that commit was what this pull request was showing.  Now I see that you copied that commit to fsm branch as well.  Because of this potential for confusion, I think Git standard practice would be to merge in that change (i.e. on your fsm branch type `git merge master`) rather than duplicating the commit on two separate branches.

**Comment by cjlee112** [comment]
Hi Evan,
I manually merged your commits on two separate branches (master and fsm), so I'm closing this pull request.  I also added additional docs on using git/github for our project.

**Comment by cjlee112** [comment]
FYI, Evan, assuming your fsm branch is still at commit aa75ae (i.e. you haven't committed additional changes after that commit), you should update it to point at my merged fsm branch (which manually merged in your changes).  To do this cleanly (i.e. to permanently get rid of the unnecessary test.txt commits), the easiest way to do this is to delete your fsm branch and re-create it pointing to my merge.  (Of course, if you've committed subsequent changes on fsm that you want to keep, do NOT do this, as `git branch -D fsm` will delete your fsm branch, causing you to lose those changes).

    git checkout master
    git branch -D fsm
    git checkout -b fsm remotes/upstream/fsm

assuming that you've setup `upstream` to point to my repo.  Let me know if you have any questions.

**Comment by wenyaowu** [comment]
Hi, Chris,

  Thanks for keeping me update. I’m still try to get familiar with the Git environment and thanks for
helping me with those tips!  I’ll rebase my FSM branch from your merge!

best, 
Evan

**Pull request closed without merging**
