### PR TITLE
Fixed expanding textarea in the chat

### PR DESCRIPTION
**Pull request by karluxd**

### CODE REVIEW

**Comment by rimikt** [comment]
@karluxd In case it is a final version - I can deploy this change for QA to test and then merge to development.

**Comment by karluxd** [comment]
Sounds good @rimikt 👍

**Comment by karluxd** [comment]
Okay, I didn't know this was a feature. As the students didn't know about ctrl+enter for newlines (it's the convention in Slack and other chat apps but not very well known), I doubt many will try to use it to submit the form. Maybe let's just merge this as is and and look at suitable keyboard shorcuts in a separate release? We could also also show some of the more the common shortcuts below the textarea 🙂

**Comment by rimikt** [comment]
@karluxd ok, let's merge this.

**Comment by rimikt** [comment]
I'll merge in another repo and close this PR. Commit will became a part of the development branch

**Comment by rimikt** [comment]
Merged and available to test on dev.courselets.org in 20 mins (after CI/CD will finish the work)

**Comment by karluxd** [comment]
Thanks @rimikt, great if we can get it out with this release. I'll add keyboard shortcuts in the backlog 🙂

**Pull request closed without merging**
